// アプリケーション内のすべてのレイアウトで共有される　ルートレイアウト
import type { Metadata } from 'next'
// Google Fonts の Inter フォントをインポート
import { Inter } from 'next/font/google'
import './globals.css'
// ラテン文字用のサブセットを設定
const inter = Inter({ subsets: ['latin'] })

// アプリ全体のメタ情報を設定
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,// will be a page or nested layout
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
